version: '3.4'

services:
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
 urlshortenerapi:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: urlshortenerapi/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"